events/config/routes.rb
Rails.application.routes.draw do
  get 'rsvp/create'
  post 'rsvp/create'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "events#index"
  resources :users
  resources :events
end

events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

events/app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :address, presence: true
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	has_many :rsvps
	has_many :users, through: :rsvps
end

events/app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user_id, uniqueness: { scope: :event_id }

end

events/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :events, dependent: :destroy
  has_many :rsvps
  has_many :events, through: :rsvps
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
	private
	def user_not_authorized
		flash[:warning] = "You are not authorized to perform this action."
		redirect_to(request.referrer || root_path)
	end
end

events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
      authorize @event
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {}).permit(:title, :description, :date, :address)
    end
end

events/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

events/app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
	def new
		@rsvp = Rsvp.new
	end
	def create
		@user = User.find_by_id(params[:user])
		@event = Event.find_by_id(params[:event])
		@rsvp = Rsvp.new({event: @event ,user: @user})
		if @rsvp.save
			RsvpmailerMailer.rsvp_email(@user,@event).deliver_later
			RsvpmailerMailer.event_reminder_email(@user,@event).deliver_later(wait_until: @event.date - 1.day)
			flash[:notice] = "RSVP sucessfull!"
		end
		redirect_to events_path
	end
	private
    ## Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = rsvp.find(params[:id])
    end

    ## Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.fetch(:rsvp, {}).permit(:user, :event)
    end
end

events/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    authorize @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:name, :email, :password, :password_confirmation)
    end
end

events/app/helpers/application_helper.rb
module ApplicationHelper
end

events/app/helpers/events_helper.rb
module EventsHelper
end

events/app/helpers/rsvp_helper.rb
module RsvpHelper
end

events/app/helpers/users_helper.rb
module UsersHelper
end

events/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :date %>
    <%= form.datetime_select :date %>
    <%= form.label :address %>
    <%= form.text_field :address %>

    <%= form.label :description %>
    <%= form.text_area :description %>

    <%= form.submit %>
  </div>
<% end %>

events/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

events/app/views/events/index.html.erb
<h1><%= link_to "Events", events_path %></h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Date</th>
			<% if user_signed_in? %>
				<th>Edit</th>
				<th>Delete</th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% @events.each do |event| %>
			<tr>
				<td><%= link_to event.title, event %></td>
				<td><%= link_to event.date.to_formatted_s(:long_ordinal), event %></td>
				<% if user_signed_in? && (current_user == event.user || current_user.try(:admin?))  %>
					<td><%= link_to 'Edit', edit_event_path(event) %></td>
					<td><%= link_to '❌', event, method: :delete, data: { confirm: 'Are you sure?' }%></td>
				<% else %>
					<td></td>
					<td></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

<br>
<% if user_signed_in? %>
	<%= button_to 'New Event', new_event_path, method: :get %>
<% end %>

events/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

events/app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p>by <%= link_to @event.user.name, @event.user %></p>
<p><strong>Date: </strong><%= @event.date.to_formatted_s(:long_ordinal) %></p>
<p><strong>Where: </strong><%= @event.address %> | <%= @event.longitude %>, <%= @event.latitude %> </p>
<div id="map"></div>
<br>
<p><%= @event.description %></p>
<% if user_signed_in? %>
<%= button_to "RSVP", :action => "create", params: { user: current_user, event: @event }, :controller => 'rsvp' %>
<% end %>
<h3>People that have RSVPed:</h3>
<% @event.users.each do |user| %>
  <h4><%= link_to user.name, user %></h4>
<% end %>
<% if user_signed_in? && (current_user == @event.user || current_user.try(:admin?))  %>
<%= link_to 'Edit Event', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
<% end %>
<script>
window.onload = setTimeout( function () {
	
  var map = L.map('map');
  var layer = Tangram.leafletLayer({
    scene: 'scene.yaml',
    attribution: '<a href="https://nextzen.org/tangram" target="_blank">Tangram</a> | &copy; OSM contributors | <a href="https://nextzen.com/" target="_blank">Nextzen</a>'
  });
  layer.addTo(map);
  map.setView([<%= @event.latitude %>,<%= @event.longitude %>], 15);
  L.marker([<%= @event.latitude %>, <%= @event.longitude %>]).addTo(map);
},1000);
</script>

events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Events</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
		<!-- CSS Reset -->
		<link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
		<!-- Milligram CSS minified -->
		<link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
	 integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
	 crossorigin=""/>
		<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
	 integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
	 crossorigin=""></script>
	 <script type="text/javascript" src="https://www.nextzen.org/tangram/0.14/tangram.min.js"></script>
	</head>
	<body>
		<div class="header">
		<div class="container">
			<p class="navbar-text pull-right">
			<%= link_to 'Home', root_path %> | 
			<% if user_signed_in? %>
				<%= link_to 'Create a new event', new_event_path %>|
				Logged in as <strong><%= current_user.name %></strong>.
				<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
				<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
				<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
				<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
			<% if current_user.try(:admin?) %>
				 | <%= link_to "Admin", users_path, :class => 'navbar-link'  %>
			<% end %>
			</p>
		</div>
		<hr>
		</div>
		<div class="container">
			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
			<%= yield %>
		</div>
		
			<hr>
			<div class="header">
			<footer class="container">
				<p>©  Martin Fibik 2019</p>
			</footer>
			</div>
	</body>
	
</html>

events/app/views/rsvp/new.html.erb
<h1>Rsvp#new</h1>
<p>Find me in app/views/rsvp/new.html.erb</p>

events/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

events/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

events/app/views/users/index.html.erb
<h1>Users</h1>

<table>
	<thead>
		<tr>
			<th colspan="5"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.name, user %></td>
				<td><%= user.email %></td>
				<td><%= link_to 'Show', user %></td>
				<td><%= link_to 'Edit', edit_user_path(user) %></td>
				<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

events/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

events/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

events/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

events/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% @user.events.each do |event| %>
  <h3><%= link_to event.title, event %></h3>
  <% if event.description %>
		<p><%= event.description.truncate(100) %></p>
  <% end %>
<% end %>